print ("Kyla Patrice Soberano Sace")
print ("170 San Antonio Street, Dawis, Gasan, Marinduque")
print ("January 09, 2002")
print ("Marinduque State College")
print ("Bachelor in Science Information Technology")
print ("2nd Year Section D")